openapi: 3.0.0
info:
  title: Covid-19 analysis around the world API
  description:
    This API provides covid-19 situation including total cases, death cases and recovered cases that occur around the world right now, 
    and the currency rate of all country in the world, and 
    Raw data provided by.
  version: 1.0.0
servers:
- url: /covid-api/v1
paths:
  /countries:
    get:
      summary: Returns a list of countries
      operationId: controller.get_countries
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Country'

  /countries/{countryId}:
    parameters:
      - name: countryId
        in: path
        required: true
        schema:
          type : integer
    get:
      summary: Returns complete details of specific country
      operationId: controller.get_country_details
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Country'

  /covid19Situation/worldSummary:
    get:
      summary: Returns covid-19 situation of the world in latest date
      operationId: controller.get_covid19_situation_world
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Covid19WorldSum'

  /covid19Situation/allCountry:
    get:
      summary: Returns a list of covid-19 situation of all country in latest date
      operationId: controller.get_covid19_situation_in_all_country
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Covid19CountrySum'

  /covid19Situation/totalCases:
    get:
      summary: Returns a list of total cases in all country in latest date
      operationId: controller.get_covid19_situation_total_cases
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Covid19CountryTotal'

  /covid19Situation/deathCases:
    get:
      summary: Returns a list of death cases in all country in latest date
      operationId: controller.get_covid19_situation_death_cases
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Covid19CountryDeath'

  /covid19Situation/recoveredCases:
    get:
      summary: Returns a list of death cases in all country in latest date
      operationId: controller.get_covid19_situation_recovered_cases
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Covid19CountryRecovered'
             
  /covid19Situation/{countryId}:
    parameters:
      - name: countryId
        in: path
        required: true
        schema:
          type : integer
    get:
      summary: Returns covid-19 situation of a specfic country in latest date
      operationId: controller.get_covid19_situation_in_specific_country
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Covid19CountrySum'
  
  /currencyRates:
    get:
      summary: Returns a list of currency rates in all country
      operationId: controller.get_currency_rates
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Currency'

  /currencyRates/{countryId}:
    parameters:
      - name: countryId
        in: path
        required: true
        schema:
          type : integer
    get:
      summary: Returns a currency rate in a specific country
      operationId: controller.get_currency_rates_in_specific_country
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Currency'

  /currencyRates/unit/{countryId}:
    parameters:
      - name: countryId
        in: path
        required: true
        schema:
          type : integer
    get:
      summary: Returns a currency unit in a specific country
      operationId: controller.get_currency_unit_in_specific_country
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/CurrencyUnit'
                  
#   /symbols:
#     get:
#       summary: Returns a list of symbols.
#       operationId: controller.get_world_currency_symbols
#       responses:
#         200:
#           description: Success
#           content:
#             application/json:
#               schema:
#                 type: array
#                 items:
#                   $ref: '#/components/schemas/Symbols'
#   /currency:
#     get:
#       summary: Returns a list of currencies.
#       operationId: controller.get_world_currency_rates
#       responses:
#         200:
#           description: Success
#           content:
#             application/json:
#               schema:
#                 items:
#                   $ref: '#/components/schemas/Currency'
#   /currency/{sym}:
#     parameters:
#     - name: sym
#       in: path
#       required: true
#       schema:
#         type : string
#     get:
#       summary: Returns complete details of the specified symbols of currency
#       operationId: controller.get_world_currency_rates_with_symbols
#       responses:
#         200:
#           description: Success
#           content:
#             application/json:
#               schema:
#                 $ref: '#/components/schemas/Currency'
#   /covid/{country}/{date}:
#     parameters:
#       - name: country
#         in: path
#         required: true
#         schema:
#           type: string
#       - name: date
#         in: path
#         required: true
#         schema:
#           type: string
#     get:
#       summary: Returns complete details of the specified covid all time
#       operationId: controller.get_covid_by_date_and_country
#       responses:
#         200:
#           description: Success
#           content:
#             application/json:
#               schema:
#                 $ref: '#/components/schemas/CovidCase'
#   /weather/{city_name}:
#     parameters:
#       - name: city_name
#         in: path
#         required: true
#         schema:
#           type: string
#       - name: unit
#         in: query
#         required: false
#         schema:
#           type: string
#         example: metric, imperial
#     get:
#       summary: Returns complete details of the weather on current time
#       operationId: controller.get_weather_currently_from_one_location
#       responses:
#         200:
#           description: Success
#           content:
#             application/json:
#               schema:
#                 $ref: '#/components/schemas/Weather'


components:
  schemas:
    Country:
      type: object
      properties:
        countryId:
          type: integer
        countryName:
          type: string
        countryAlpha:
          type: string
          description: First 3 alphabet of country name

    Covid19WorldSum:
      type: object
      properties:
        totalCases:
          type: integer
        deathCases:
          type: integer
        recoveredCases:
          type: integer
        date:
          type: date
    
    Covid19CountrySum:
      type: object
      properties:
        countryId:
          type: integer
        countryName:
          type: string
        totalCases:
          type: integer
        deathCases:
          type: integer
        recoveredCases:
          type: integer
        date:
          type: date

    Covid19CountryTotal:
      type: object
      properties:
        countryId:
          type: integer
        countryName:
          type: string
        totalCases:
          type: integer
        date:
          type: date

    Covid19CountryDeath:
      type: object
      properties:
        countryId:
          type: integer
        countryName:
          type: string
        deathCases:
          type: integer
        date:
          type: date

    Covid19CountryRecovered:
      type: object
      properties:
        countryId:
          type: integer
        countryName:
          type: string
        recoveredCases:
          type: integer
        date:
          type: date

    Currency:
      type: object
      properties:
        countryId:
          type: integer
        countryName:
          type: string
        currencyRates:
          type: number
        currencyUnit:
          type: string

    CurrencyUnit:
      type: object
      properties:
        countryId:
          type: integer
        countryName:
          type: string
        currencyUnit:
          type: string






# components:
#   schemas:
#     Currency:
#       type: object
#       properties:
#         rates:
#           type: number
#         base:
#           type: string
#         date:
#           type: string
#     Symbols:
#       type: object
#       properties:
#         symbols:
#           type: string
#     CovidCase:
#       type: object
#       properties:
#         country:
#           type: string
#         confirmed:
#           type: number
#         deaths:
#           type: number
#     Weather:
#       type: object
#       properties:
#         name:
#           type: string
#         country:
#           type: string
#         temp:
#           type: number
#         feels_like:
#           type: number
#         temp_min:
#           type: number
#         temp_max:
#           type: number
#         pressure:
#           type: number
#         humidity:
#           type: number
