openapi: 3.0.0
info:
  title: Covid-19 analysis around the world API
  description:
    This API provides covid-19 situation including total cases, death cases and recovered cases that occur around the world right now, 
    and the currency rate of all country in the world, and 
    Raw data provided by.
  version: 1.0.0
servers:
- url: /covid-api/v1
paths:
  /countries:
    get:
      summary: Returns a list of countries
      operationId: controller.get_countries
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Country'

  /countries/{countryId}:
    parameters:
      - name: countryId
        in: path
        required: true
        schema:
          type : integer
    get:
      summary: Returns complete details of specific country
      operationId: controller.get_country_details
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Country'

  /covid19Situation/summary/world:
    get:
      summary: Returns covid-19 situation summary of the world in latest date
      operationId: controller.get_sum_covid19_situation_world_latest
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Covid19WorldSum'

  /covid19Situation/newCases/world:
    get:
      summary: Returns covid-19 new cases of the world
      operationId: controller.get_new_covid19_situation_world
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Covid19WorldNew'

  /covid19Situation/summary/allCountry:
    get:
      summary: Returns a list of covid-19 situation summary of all country in latest date
      operationId: controller.get_sum_covid19_situation_in_all_country_latest
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Covid19CountrySum'

  /covid19Situation/newCases/allCountry:
    get:
      summary: Returns a list of covid-19 new cases of all country
      operationId: controller.get_new_covid19_situation_in_all_country
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Covid19CountryNew'

  /covid19Situation/newCases/{countryId}:
    parameters:
      - name: countryId
        in: path
        required: true
        schema:
          type : integer
    get:
      summary: Returns a list of covid-19 new cases of specific country
      operationId: controller.get_new_covid19_situation_in_specific_country
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Covid19CountryNew'

  /currencyRates/{countryId}:
    parameters:
      - name: countryId
        in: path
        required: true
        schema:
          type : integer
    get:
      summary: Returns a currency rate in a specific country
      operationId: controller.get_currency_rate_in_specific_country
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Currency'

  /currencyRates/unit/{countryId}:
    parameters:
      - name: countryId
        in: path
        required: true
        schema:
          type : integer
    get:
      summary: Returns a currency unit in a specific country
      operationId: controller.get_currency_unit_in_specific_country
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/CurrencyUnit'

components:
  schemas:
    Country:
      type: object
      properties:
        countryId:
          type: integer
        countryName:
          type: string
        countryAlpha2:
          type: string
          description: 2-alphabets country code represents each country
        countryAlpha3:
          type: string
          description: 3-alphabets country code represents each country

    Covid19WorldSum:
      type: object
      properties:
        totalCases:
          type: integer
        totaldeathCases:
          type: integer
        totalrecoveredCases:
          type: integer
        date:
          type: date

    Covid19WorldNew:
      type: object
      properties:
        Location:
          type: string
        newCases:
          type: integer
        newDeath:
          type: integer
        date:
          type: date
    
    Covid19CountrySum:
      type: object
      properties:
        countryId:
          type: integer
        countryName:
          type: string
        totalCases:
          type: integer
        totalDeathCases:
          type: integer
        totalRecoveredCases:
          type: integer
        date:
          type: date

    Covid19CountryNew:
      type: object
      properties:
        countryId:
          type: integer
        countryName:
          type: string
        newCases:
          type: integer
        newDeath:
          type: integer
        date:
          type: date

    Currency:
      type: object
      properties:
        countryId:
          type: integer
        countryName:
          type: string
        currencyRates:
          type: number
        currencyUnit:
          type: string
        date:
          type: date

    CurrencyUnit:
      type: object
      properties:
        countryName:
          type: string
        currencyUnit:
          type: string
