openapi: 3.0.0
info:
  title: Asia Covid-19 API
  description:
    This API provides historical rainfall data over upper Chaopraya river basin between 1987
    and 2019.  Raw data provided by Thai Meteorological Department (TMD).
  version: 1.0.0
servers:
- url: /covid-api/v1
paths:
  /symbols:
    get:
      summary: Returns a list of symbols.
      operationId: controller.get_world_currency_symbols
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Symbols'
  /currency:
    get:
      summary: Returns a list of currencies.
      operationId: controller.get_world_currency_rates
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/Currency'
  /currency/{sym}:
    parameters:
    - name: sym
      in: path
      required: true
      schema:
        type : string
    get:
      summary: Returns complete details of the specified symbols of currency
      operationId: controller.get_world_currency_rates_with_symbols
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Currency'
  /covid/{country}/{date}:
    parameters:
      - name: country
        in: path
        required: true
        schema:
          type: string
      - name: date
        in: path
        required: true
        schema:
          type: string
    get:
      summary: Returns complete details of the specified covid all time
      operationId: controller.get_covid_by_date_and_country
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CovidCase'
  /weather/{city_name}:
    parameters:
      - name: city_name
        in: path
        required: true
        schema:
          type: string
      - name: unit
        in: query
        required: false
        schema:
          type: string
        example: metric, imperial
    get:
      summary: Returns complete details of the weather on current time
      operationId: controller.get_weather_currently_from_one_location
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Weather'

components:
  schemas:
    Currency:
      type: object
      properties:
        rates:
          type: number
        base:
          type: string
        date:
          type: string
    Symbols:
      type: object
      properties:
        symbols:
          type: string
    CovidCase:
      type: object
      properties:
        country:
          type: string
        confirmed:
          type: number
        deaths:
          type: number
    Weather:
      type: object
      properties:
        name:
          type: string
        country:
          type: string
        temp:
          type: number
        feels_like:
          type: number
        temp_min:
          type: number
        temp_max:
          type: number
        pressure:
          type: number
        humidity:
          type: number
