openapi: 3.0.0
info:
  title: Covid-19 analysis around the world API
  description:
    This API provides covid-19 situation including total cases, death cases and recovered cases that occur around the world right now, 
    and the currency rate of all country in the world, and 
    Raw data provided by.
  version: 1.0.0
servers:
- url: /covid-api/v1
paths:
  /countries:
    get:
      summary: Returns a list of countries
      operationId: controller.get_countries
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Country'

  /countries/{countryId}:
    parameters:
      - name: countryId
        in: path
        required: true
        schema:
          type : integer
    get:
      summary: Returns complete details of specific country
      operationId: controller.get_country_details
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Country'

  /covid19Situation/summary/world:
    get:
      summary: Returns covid-19 situation summary of the world in latest date
      operationId: controller.get_sum_covid19_situation_world
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Covid19WorldSum'

  /covid19Situation/newCases/world:
    get:
      summary: Returns covid-19 new cases of the world in latest date
      operationId: controller.get_new_covid19_situation_world
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Covid19WorldNew'

  /covid19Situation/summary/allCountry:
    get:
      summary: Returns a list of covid-19 situation summary of all country in latest date
      operationId: controller.get_sum_covid19_situation_in_all_country
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Covid19CountrySum'

  /covid19Situation/newCases/allCountry:
    get:
      summary: Returns a list of covid-19 new cases of all country in latest date
      operationId: controller.get_new_covid19_situation_in_all_country
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Covid19CountryNew'

  /covid19Situation/newCases/{countryId}:
    parameters:
      - name: countryId
        in: path
        required: true
        schema:
          type : integer
    get:
      summary: Returns a list of covid-19 new cases of all country in latest date
      operationId: controller.get_new_covid19_situation_in_specific_country
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Covid19CountryNew'

  /covid19Situation/totalCases:
    get:
      summary: Returns a list of total cases in all country in latest date
      operationId: controller.get_covid19_situation_total_cases
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Covid19CountryTotal'

  /covid19Situation/deathCases:
    get:
      summary: Returns a list of death cases in all country in latest date
      operationId: controller.get_covid19_situation_death_cases
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Covid19CountrySumDeath'

             
  /covid19Situation/newCases:
    get:
      summary: Returns list of new cases occur in all country in latest date
      operationId: controller.get_covid19_situation_new_cases
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Covid19CountryNewCases'

  /covid19Situation/newDeath:
    get:
      summary: Returns list of new death occur in all country in latest date
      operationId: controller.get_covid19_situation_new_death
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Covid19CountryNewDeath'

  /covid19Situation/newRecovered:
    get:
      summary: Returns list of new recovered occur in all country in latest date
      operationId: controller.get_covid19_situation_new_recovered
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Covid19CountryNewRecovered'

  /covid19Situation/{countryId}:
    parameters:
      - name: countryId
        in: path
        required: true
        schema:
          type : integer
    get:
      summary: Returns all covid-19 information of a specfic country in latest date
      operationId: controller.get_covid19_information_in_specific_country
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                 $ref: '#/components/schemas/Covid19CountryAll'
  
  /currencyRates:
    get:
      summary: Returns a list of currency rates in all country
      operationId: controller.get_currency_rates
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Currency'

  /currencyRates/{countryId}:
    parameters:
      - name: countryId
        in: path
        required: true
        schema:
          type : integer
    get:
      summary: Returns a currency rate in a specific country
      operationId: controller.get_currency_rate_in_specific_country
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Currency'

  /currencyRates/unit/{countryId}:
    parameters:
      - name: countryId
        in: path
        required: true
        schema:
          type : integer
    get:
      summary: Returns a currency unit in a specific country
      operationId: controller.get_currency_unit_in_specific_country
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Currency'

components:
  schemas:
    Country:
      type: object
      properties:
        countryId:
          type: integer
        countryName:
          type: string
        countryAlpha2:
          type: string
          description: 2-alphabets country code represents each country
        countryAlpha3:
          type: string
          description: 3-alphabets country code represents each country

    Covid19WorldSum:
      type: object
      properties:
        totalCases:
          type: integer
        deathCases:
          type: integer
        recoveredCases:
          type: integer
        date:
          type: date

    Covid19WorldNew:
      type: object
      properties:
        newCases:
          type: integer
        newDeath:
          type: integer
        newRecovered:
          type: integer
        date:
          type: date
    
    Covid19CountrySum:
      type: object
      properties:
        countryId:
          type: integer
        countryName:
          type: string
        totalCases:
          type: integer
        totalDeathCases:
          type: integer
        totalRecoveredCases:
          type: integer
        date:
          type: date

    Covid19CountryNew:
      type: object
      properties:
        countryId:
          type: integer
        countryName:
          type: string
        newCases:
          type: integer
        newDeath:
          type: integer
        date:
          type: date

    Covid19CountryTotal:
      type: object
      properties:
        countryId:
          type: integer
        countryName:
          type: string
        totalCases:
          type: integer
        date:
          type: date

    Covid19CountrySumDeath:
      type: object
      properties:
        countryId:
          type: integer
        countryName:
          type: string
        totalDeathCases:
          type: integer
        date:
          type: date

    Covid19CountryNewCases:
      type: object
      properties:
        countryId:
          type: integer
        countryName:
          type: string
        newCases:
          type: integer
        date:
          type: date

    Covid19CountryNewDeath:
      type: object
      properties:
        countryId:
          type: integer
        countryName:
          type: string
        newDeath:
          type: integer
        date:
          type: date

    Covid19CountryNewRecovered:
      type: object
      properties:
        countryId:
          type: integer
        countryName:
          type: string
        newRecovered:
          type: integer
        date:
          type: date

    Covid19CountryAll:
      type: object
      properties:
        countryId:
          type: integer
        countryName:
          type: string
        totalCases:
          type: integer
        totalDeathCases:
          type: integer
        totalRecoveredCases:
          type: integer
        newCases:
          type: integer
        newDeath:
          type: integer
        newRecovered:
          type: integer
        date:
          type: date

    Currency:
      type: object
      properties:
        countryId:
          type: integer
        countryName:
          type: string
        currencyRates:
          type: number
        currencyUnit:
          type: string
        date:
          type: date



#   /symbols:
#     get:
#       summary: Returns a list of symbols.
#       operationId: controller.get_world_currency_symbols
#       responses:
#         200:
#           description: Success
#           content:
#             application/json:
#               schema:
#                 type: array
#                 items:
#                   $ref: '#/components/schemas/Symbols'
#   /currency:
#     get:
#       summary: Returns a list of currencies.
#       operationId: controller.get_world_currency_rates
#       responses:
#         200:
#           description: Success
#           content:
#             application/json:
#               schema:
#                 items:
#                   $ref: '#/components/schemas/Currency'
#   /currency/{sym}:
#     parameters:
#     - name: sym
#       in: path
#       required: true
#       schema:
#         type : string
#     get:
#       summary: Returns complete details of the specified symbols of currency
#       operationId: controller.get_world_currency_rates_with_symbols
#       responses:
#         200:
#           description: Success
#           content:
#             application/json:
#               schema:
#                 $ref: '#/components/schemas/Currency'
#   /covid/{country}/{date}:
#     parameters:
#       - name: country
#         in: path
#         required: true
#         schema:
#           type: string
#       - name: date
#         in: path
#         required: true
#         schema:
#           type: string
#     get:
#       summary: Returns complete details of the specified covid all time
#       operationId: controller.get_covid_by_date_and_country
#       responses:
#         200:
#           description: Success
#           content:
#             application/json:
#               schema:
#                 $ref: '#/components/schemas/CovidCase'
#   /weather/{city_name}:
#     parameters:
#       - name: city_name
#         in: path
#         required: true
#         schema:
#           type: string
#       - name: unit
#         in: query
#         required: false
#         schema:
#           type: string
#         example: metric, imperial
#     get:
#       summary: Returns complete details of the weather on current time
#       operationId: controller.get_weather_currently_from_one_location
#       responses:
#         200:
#           description: Success
#           content:
#             application/json:
#               schema:
#                 $ref: '#/components/schemas/Weather'







# components:
#   schemas:
#     Currency:
#       type: object
#       properties:
#         rates:
#           type: number
#         base:
#           type: string
#         date:
#           type: string
#     Symbols:
#       type: object
#       properties:
#         symbols:
#           type: string
#     CovidCase:
#       type: object
#       properties:
#         country:
#           type: string
#         confirmed:
#           type: number
#         deaths:
#           type: number
#     Weather:
#       type: object
#       properties:
#         name:
#           type: string
#         country:
#           type: string
#         temp:
#           type: number
#         feels_like:
#           type: number
#         temp_min:
#           type: number
#         temp_max:
#           type: number
#         pressure:
#           type: number
#         humidity:
#           type: number
