openapi: 3.0.0
info:
  description: This API provides historical rainfall data over upper Chaopraya river
    basin between 1987 and 2019.  Raw data provided by Thai Meteorological Department
    (TMD).
  title: Asia Covid-19 API
  version: 1.0.0
servers:
- url: /covid-api/v1
paths:
  /currency:
    get:
      operationId: controller_get_world_currency_rates
      responses:
        "200":
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/Currency'
                type: array
          description: Success
      summary: Returns a list of currencies.
      x-openapi-router-controller: openapi_server.controllers.default_controller
  /currency/{sym}:
    get:
      operationId: controller_get_world_currency_rates_with_symbols
      parameters:
      - explode: false
        in: path
        name: sym
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Currency'
          description: Success
      summary: Returns complete details of the specified symbols of currency
      x-openapi-router-controller: openapi_server.controllers.default_controller
  /symbols:
    get:
      operationId: controller_get_world_currency_symbols
      responses:
        "200":
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/Symbols'
                type: array
          description: Success
      summary: Returns a list of symbols.
      x-openapi-router-controller: openapi_server.controllers.default_controller
components:
  schemas:
    Currency:
      example:
        date: date
        rates: 0.8008281904610115
        base: base
      properties:
        rates:
          type: number
        base:
          type: string
        date:
          type: string
      type: object
    Symbols:
      example:
        symbols: symbols
      properties:
        symbols:
          type: string
      type: object
